### ISSUE TITLE
Curly quotes prevent a slack message from showing up in minecraft

### ISSUE THREAD

**Issue by kkuchta** [qrush/wither#7]
Regular quotes: `"foo"`
Curly quotes : `“foo”`

If, on a mac, you have "Use smart quotes" enabled under System Preferences > Keyboard > Text, typing `"foo"` in many programs will automatically convert to curly quotes (`“foo”`).  Slack is one such program.

However, any message in slack containing curly quotes will fail to show up in minecraft, while the same message with regular quotes will show up fine.

**Comment by qrush** [comment]
This seems fixed now.
